return {
	{
		"oncomouse/lushwal.nvim",
		cmd = { "LushwalCompile" },
		dependencies = {
			{ "rktjmp/lush.nvim" },
			{ "rktjmp/shipwright.nvim" },
		},
		config = function()
			require("lushwal").setup({
				ale = false,
				barbar = false,
				bufferline_nvim = true,
				coc_nvim = false,
				dashboard_nvim = false,
				fern_vim = false,
				gina = false,
				gitsigns_nvim = true,
				hop_nvim = false,
				hydra_nvim = false,
				indent_blankline_nvim = true,
				lightspeed_nvim = false,
				lspsaga_nvim = false,
				lsp_trouble_nvim = true,
				lualine = true,
				markdown = true,
				mini_nvim = false,
				native_lsp = true,
				neogit = true,
				neomake = false,
				nerdtree = false,
				nvim_cmp = true,
				nvim_tree_lua = true,
				nvim_ts_rainbow = true,
				semshi = false,
				telescope_nvim = true,
				treesitter = true,
				vim_dirvish = false,
				vim_gitgutter = false,
				vim_signify = false,
				vim_sneak = false,
				which_key_nvim = true,
			})
		end,
	},
}
